repos:
  - repo: local
    hooks:
      - id: imports
        name: "Import Linter"
        language: system
        pass_filenames: false
        entry: lint-imports
        verbose: true

  - repo: local
    hooks:
      - id: BDD tests
        name: "behave tests"
        language: system
        pass_filenames: false
        entry: behave
        verbose: true

  - repo: local
    hooks:
      - id: Pytests tests
        name: "pytest tests"
        language: system
        pass_filenames: false
        entry: pytest
        verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml # Checks yaml files for parseable syntax.
      - id: check-json # Checks json files for parseable syntax.
      - id: check-added-large-files
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: requirements-txt-fixer # Sorts entries in requirements.txt

  - repo: https://github.com/psf/black
    rev: 24.4.2  # Updated to the latest stable version
    hooks:
      - id: black
        language_version: python3.10
        args: ['-l', '80', '--check', '--diff']
        files: src/python/  # Ensure Black only checks the Python source directory
        verbose: true
