repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml # Checks yaml files for parseable syntax.
      - id: check-json # Checks json files for parseable syntax.
      - id: check-added-large-files
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: requirements-txt-fixer # Sorts entries in requirements.txt

  - repo: https://github.com/psf/black
    rev: 24.4.2  # Updated to the latest stable version
    hooks:
      - id: black
        language_version: python3.10
        args: ['-l', '80', '--check', '--diff']
        files: src/python/  # Ensure Black only checks the Python source directory

  - repo: local
    hooks:
      - id: go_mod_tidy
        name: "Go Mod Tidy"
        entry: >
          python -c "import subprocess; subprocess.run(['go', 'mod', 'tidy'], cwd='src/go')"
        language: python
        types: [go]

  - repo: local
    hooks:
      - id: imports
        name: "Import Linter"
        entry: >
          python -c "import subprocess; subprocess.run(['lint-imports'], cwd='src/python')"
        language: python
        types: [python]
