repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Updated to the latest stable version
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.4.2  # Updated to the latest stable version
    hooks:
      - id: black
        language_version: python3.10
        args: ['-l', '80', '--check', '--diff']
        files: src/python/  # Ensure Black only checks the Python source directory

  - repo: local
    hooks:
      - id: go_mod_tidy
        name: Go Mod Tidy
        entry: bash -c 'cd src/go && go mod tidy'
        language: system
        types: [go]
