[tool.importlinter]
root_package = "notificationservice"

[[tool.importlinter.contracts]]
name = "Notifications depend on Rate Limiter and Config"
type = "layers"
containers = "notificationservice"
layers = [
    "infra",
    "config",
    "rate_limiter",
    "notifications"
]
ignore_imports = []

[[tool.importlinter.contracts]]
name = "Rate Limiter does not depend on Notifications"
type = "forbidden"
source_modules = [
    "notificationservice.rate_limiter"
]
forbidden_modules = [
    "notificationservice.notifications"
]

[[tool.importlinter.contracts]]
name = "Infraestructure does not depend on nothing"
type = "forbidden"
source_modules = [
    "notificationservice.infra"
]
forbidden_modules = [
    "notificationservice.notifications",
    "notificationservice.api",
    "notificationservice.config",
    "notificationservice.notifications",
    "notificationservice.rate_limiter"
]

[[tool.importlinter.contracts]]
name = "Config is independent"
type = "independence"
modules = [
    "notificationservice.config"
]

[[tool.importlinter.contracts]]
name = "API depends on Notifications and Rate Limiter"
type = "layers"
containers = "notificationservice"
layers = [
    "infra",
    "rate_limiter",
    "notifications",
    "api"
]
ignore_imports = []

[pytest]


env = [
    "MODAK_TEST_MODE=1",
    "MODAK_DATABASE_CONNECTION_URL=sqlite+aiosqlite:////tmp/marvin/marvin-tests.sqlite",
    "MODAK_LOG_CONSOLE_WIDTH=120",
]

# black configuration
[tool.black]
preview = true

# ruff configuration
[tool.ruff]
extend-select = ["I"]

[tool.ruff.per-file-ignores]
"__init__.py" = ['I', 'F401', 'E402']
"conftest.py" = ["F401", "F403"]
'tests/fixtures/*.py' = ['F403']
