[tool.importlinter]
root_package = "notificationserver"

[[tool.importlinter.contracts]]
name = "Notifications depend on Rate Limiter and Config"
type = "layers"
containers = "modak"
layers = [
    "config",
    "rate_limiter",
    "notifications"
]
ignore_imports = []

[[tool.importlinter.contracts]]
name = "Rate Limiter does not depend on Notifications"
type = "forbidden"
source_modules = [
    "modak.rate_limiter"
]
forbidden_modules = [
    "modak.notifications"
]

[[tool.importlinter.contracts]]
name = "Config is independent"
type = "independence"
modules = [
    "modak.config"
]

[[tool.importlinter.contracts]]
name = "API depends on Notifications and Rate Limiter"
type = "layers"
containers = "modak"
layers = [
    "rate_limiter",
    "notifications",
    "api"
]
ignore_imports = []
